seed_everything: 123
model:
  pytorch_model:
    class_path: models.mf.MatrixFactorization
    init_args:
      n_users: 943
      n_items: 1625
      n_factors: 64
  learning_rate: 0.012
  weight_decay: 0.001
data:
  class_path: datasets.movielens.MovielensDataModule
  init_args:
    dataset: ml-100k
    target: rating
    batch_size: 4096
trainer:
  max_epochs: 10
  log_every_n_steps: 10
  accelerator: mps
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs
      name: ${model.pytorch_model.class_path}
      sub_dir: tf_logs
