seed_everything: 123
model:
  pytorch_model:
    class_path: models.mf.MatrixFactorization
    init_args:
      n_users: 943
      n_items: 1625
      n_factors: 128
  learning_rate: 0.012
  weight_decay: 0.001
data:
  class_path: datasets.movielens.MovielensDataModule
  init_args:
    dataset: ml-100k
    target: rating
    batch_size: 4096
trainer:
  log_every_n_steps: 10
  accelerator: mps
  devices: 1
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs
      name: ${model.pytorch_model.class_path}
      version: null
      sub_dir: tf_logs
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      save_top_k: 1
      mode: min
      monitor: valid_loss
      save_last: true
      filename: best_model
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: valid_loss
      min_delta: 0.0
      patience: 5
      verbose: false
      mode: min
  fast_dev_run: false
  max_epochs: 30
  deterministic: true


